### ISSUE TITLE
[Task] Create a real profile page

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/client-store#62]
## What should be done 
Replace the menu of the home page by a link to the profil page (with an icon) and create sections in the profil page to handle what is in the menu.

This will let us add more elements to the profil page later.

## Technical recommandation
Use an existing page template to use the same design

**Comment by jonas-martinez** [comment]
@taorepoara I can take care of this feature but I will need someone to do the design beforehand.

**Comment by taorepoara** [comment]
We can see that together today :smiley:

**Comment by taorepoara** [comment]
Resolved by #64
