### ISSUE TITLE
[Task] CI - Release the Android client

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/client-store#66]
## What should be done 
In every release, also release the Android client targeting the production server.

## Technical recommandation
This build should not be done on dev branches in order to speedup the CI. But a [manual workflow](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) can be created to run it for a test.

## Ecological concerns
Do not run the build every time but only for release.

**Comment by jonas-martinez** [comment]
@taorepoara It worked as you can see here https://github.com/lenra-io/client/releases/tag/v1.0.0-alpha.4 .
Feel free to reopen this issue if you find anything to add
