### ISSUE TITLE
[Bug]: Loading Lenra logo from mobile browsers

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/client-store#76]
### What happened?

The Lenra logos from the login and register pages are not displayed on mobile devices browsers.

The problem occurse on Android and iOS.

### What browsers are you seeing the problem on?

Firefox, Chrome (or chrome-based), Safari

**Comment by taorepoara** [comment]
I think this comes from that all the images are not in the `2.0x`  and `3.0x` directories: https://github.com/lenra-io/client/tree/beta/assets/images

**Comment by shiipou** [comment]
I didn't have this issue on my side.

@lenra-io/devs Can someone confirm me that the problem must show on that screens ?


![Screenshot_20231009-103702.png](https://github.com/lenra-io/client/assets/38187238/2aebfb82-fe82-4538-9c44-8a93a90a6797)

![Screenshot_20231009-103712.png](https://github.com/lenra-io/client/assets/38187238/b731dcdf-aa73-4291-a05d-b4d7b4c687b2)

![Screenshot_20231009-103709.png](https://github.com/lenra-io/client/assets/38187238/fc64e868-05d5-4cd2-846d-96ee98f15851)

**Comment by jonas-martinez** [comment]
@shiipou I can confirm that the images are properly working on production. I'm closing this issue as it was created before the OAuth implementation. @taorepoara feel free to reopen this issue if you find any related problem.
